// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "server.h"

//#include "utils/ir/ir_instance.h"
#include "utils/mask/mask_impl.h"


std::string server::processVideo(const std::string& path) {
  return "";
}
