// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#include "server.h"

// OpenCV libraries
#include <opencv2/opencv.hpp>

#include "utils/mask/mask_impl.h"


std::string server::processVideo(const std::string& path) {
  cv::Mat m;
  return "";
}
