// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef SERVER_H
#define SERVER_H

#include <ngrest/common/Service.h>

//! V-commerce backend server
/*! V-commerce backend server. */
// *location: server
class server: public ngrest::Service {
 public:
  //! Receives an image and detects objects inside the image
  /*! Receives an image and detects objects inside the image.
   * This method returns a token which will be used to get
   * the result once it is available.
   */
  // *location: /processVideo
  // *method: POST
  //
  std::string processVideo(const std::string& path);
};


#endif // SERVER_H



